package io.github.albinberisha.future.api.domain.enums;

/**
 * @author Albin Berisha <albin199915@gmail.com>
 *
 */
public enum UserPermission {
	CREATE_USER,
	VIEW_USER,
	UPDATE_USER,
	DELETE_USER,

	CREATE_USER_ROLE,
	VIEW_USER_ROLE,
	UPDATE_USER_ROLE,
	DELETE_USER_ROLE,

	CREATE_MERCHANT,
	VIEW_MERCHANT,
	UPDATE_MERCHANT,
	DELETE_MERCHANT,

	CREATE_STORE,
	VIEW_STORE,
	UPDATE_STORE,
	DELETE_STORE,

	VIEW_STORE_FEATURE,

	CREATE_PRODUCT,
	VIEW_PRODUCT,
	UPDATE_PRODUCT,
	DELETE_PRODUCT,

	CREATE_PRODUCT_CATEGORY,
	VIEW_PRODUCT_CATEGORY,
	UPDATE_PRODUCT_CATEGORY,
	DELETE_PRODUCT_CATEGORY,

	CREATE_PRODUCT_FILTER
}
